### PR TITLE
Return non-null writable for defined defaultValue

### LINKED ISSUE #75: Value is nullable if default value is provided
### Describe the bug

image

type of `page` should be `Writable<number>`

### Reproduction

```svelte
<script>
  import { queryParam, ssp } from "sveltekit-search-params";

  $: page = queryParam("p", ssp.number());
</script>
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by gwax**
This change modifies the return type of queryParam to be Writable<T> instead of Writable<T | null> if options is included and specifies a defaultValue.

We additionally modify the various ssp helper functions to return Writable<T> instead of Writable<T | null> when a default value is provided.

Fixes #75

## Summary by CodeRabbit

- **New Features**
	- Introduced dedicated functions for encoding and decoding various data types, enhancing modularity and flexibility.
	- Improved `queryParam` function with new overloads for more flexible usage.

- **Improvements**
	- Enhanced type safety by centralizing encoding and decoding logic within new functions.
	- Updated export structure for clearer delineation of encoding and decoding strategies, improving readability.
	- Ensured non-null writable values are returned when a `defaultValue` is provided, enhancing module reliability.
	- Modernized workflow configurations to utilize the latest versions of tools, enhancing performance and reliability.

### CODE REVIEW

**Comment by paoloricciuti** [comment]
Uh this is nice. I tried to do something like this for a long time and failed to do so. I will try to take a look today or tomorrow or else I will get to it on Monday, thanks for contributing

**Comment by gwax** [comment]
Yeah, getting types right is a challenge. I wasn't feeling up to figuring out how to make `queryParameters` work right. I think this implementation is pretty straightforward, though it's pretty verbose to get `ssp` to work right 🤷 .

It's a great library and it'll be nice to avoid casting my `Writable<string | null>` to `Writable<string>`.

Please let me know if there's anything that I can do or clarify to help with your review process.

**Comment by paoloricciuti** [comment]
Hey @gwax great work...i pushed a small fix for `queryParam` that was defaulting to unknown when no encode and decode options was passed.

There's a typing problem with `queryParameters` tho that i've yet to figure out how to solve so i'm pushing the fix to `queryParam` in the meantime. If you have any idea how to fix this please go ahead.

```ts
const store: Writable<LooseAutocomplete<{
    str: unknown;
    num: number;
    bools: boolean;
    obj: {
        str: string;
    };
    arr: number[];
    lz: string;
}>>
```
this is the type that i'm getting back in `./playground/src/routes/queryparameters/+page.svelte` where the store is defined like so:

```ts
const store = queryParameters({
	str: true,
	num: ssp.number(),
	bools: ssp.boolean(),
	obj: ssp.object<{ str: string }>(),
	arr: ssp.array<number>(),
	lz: ssp.lz<string>(),
});
```
in theory the expected type for this should be
```ts
const store: Writable<LooseAutocomplete<{
    str: string | null;
    num: number | null;
    bools: boolean | null;
    obj: {
        str: string;
    } | null;
    arr: number[] | null;
    lz: string | null;
}>>
```
and obviously passing an option with a default should also work there. I'll try to see if i can figure ths out

**Comment by paoloricciuti** [comment]
Oh i'm actually an idiot: this was already like this in older versions...so no fault from you here sorry.

Let me see if i can make something work.

**Comment by paoloricciuti** [comment]
@gwax i actually did it (the types for `queryParameters` were much simpler than what you did and it seems to work fine. Just need to check if this change in types is not a breaking change and then i'll merge and publish a new release. Thanks a lot!

**Review by paoloricciuti — APPROVED** [review]

**Pull request merged**
